/*******************************************************************************
  * @file    acu_ddr.c
  * @author  Denglin SOC Team
  * @version V1.0.0
  * @date    03-Augest-2018
  * @brief   ACU DDR Module Function. 
 ******************************************************************************/
#include "acu_ddr.h"
#include "i2c_passive.h"

void PCIE_DeInit(void)
{

}

void PCIE_Init(void)
{
    /* command register configuration */
    WRITE32(ACU_PCIE_BASE + 4, 0x7);
    WRITE32(ACU_PCIE_BASE + 0x10, 0x0);
    WRITE32(ACU_PCIE_BASE + 0x14, 0x1000000);
    WRITE32(ACU_PCIE_BASE + 0x18, 0x10000000);
    WRITE32(ACU_PCIE_BASE + 0x1C, 0x20000000);
    WRITE32(ACU_PCIE_BASE + 0x20, 0x30000000);
    WRITE32(ACU_PCIE_BASE + 0x24, 0x40000000);
}

void ELBI_WriteAccess(uint32_t Addr, uint32_t Data)
{
    WRITE32(0x40008E00, Addr);
    WRITE32(0x40008E04, Data);
}

uint32_t ELBI_ReadAccess(uint32_t Addr)
{
    WRITE32(0x40008E08, Addr);
    
    return READ32(0x40008E0C);
}

void PCIE_PrintReg(void)
{
    DEBUG_PRINT_REG(PCIE_SC);

    DEBUG_PRINT_REG(PCIE_SC->REGISTER0);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER1);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER2);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER3);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER4);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER5);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER6);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER7);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER8);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER9);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER10);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER11);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER12);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER13);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER14);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER15);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER16);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER17);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER18);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER19);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER20);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER21);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER22);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER23);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER24);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER25);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER26);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER27);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER28);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER29);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER30);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER31);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER32);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER33);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER34);
    DEBUG_PRINT_REG(PCIE_SC->REGISTER35);
    
    DEBUG_PRINT_REG(PCIE_SC->DBI_SEL);
    DEBUG_PRINT_REG(PCIE_SC->PHY_LOS_BIAS);
    DEBUG_PRINT_REG(PCIE_SC->PHY_LOS_LEVEL);
    DEBUG_PRINT_REG(PCIE_SC->PHY_RX0_EQ);
    DEBUG_PRINT_REG(PCIE_SC->PHY_TX_DEEMPH_GEN23);
    DEBUG_PRINT_REG(PCIE_SC->PHY_TX_DEEMPH_GEN26);
    DEBUG_PRINT_REG(PCIE_SC->PHY_TX_DEEMPH_GEN1);
    DEBUG_PRINT_REG(PCIE_SC->PCS_TX_SWING_FULL);
    DEBUG_PRINT_REG(PCIE_SC->PCS_TX_SWING_LOW);
    DEBUG_PRINT_REG(PCIE_SC->PHY_TX0_TERM_OFT);
    DEBUG_PRINT_REG(PCIE_SC->PHY_TX_VBOOST_1V1);
    DEBUG_PRINT_REG(PCIE_SC->VREG_BYPASS);
}

